import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Menubar from "./components/layout/Menubar";
import Footer from "./components/layout/Footer";
import ClientSessionProvider from "./providers/ClientSessionProvider";
import ClientThemeProvider from "./providers/ClientThemeProvider";

  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body >
        <ClientSessionProvider>

          {/* 다크 모드 적용된 메뉴바*/}
          <ClientThemeProvider/>
          {/* 메뉴바 */}
          {/* <Menubar/> */}
          
          {children}
          
          {/* Footer */}
          <Footer/>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
