import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menubar from "./components/common/Menubar";
import Footer from "./components/common/Footer";
import ClientSessionProvider from "./components/ClientSessionProvider";

  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientSessionProvider>
          {/* 메뉴바 */}
          <Menubar/>
          
          {children}
          
          {/* Footer */}
          <Footer/>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
